-- Drop tables if they exist
DROP TABLE IF EXISTS Updates;
DROP TABLE IF EXISTS Records;
DROP TABLE IF EXISTS Transact;
DROP TABLE IF EXISTS Department_acc;
DROP TABLE IF EXISTS Assembly_acc;
DROP TABLE IF EXISTS Process_acc;
DROP TABLE IF EXISTS Department;
DROP TABLE IF EXISTS Supervise;
DROP TABLE IF EXISTS Manufacture;
DROP TABLE IF EXISTS Cut_Job;
DROP TABLE IF EXISTS Paint_Job;
DROP TABLE IF EXISTS Fit_Job;
DROP TABLE IF EXISTS Job;
DROP TABLE IF EXISTS Cut;
DROP TABLE IF EXISTS Paint;
DROP TABLE IF EXISTS Fit;
DROP TABLE IF EXISTS Process;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Assembly;
DROP TABLE IF EXISTS Customer;

